name: Test Integrations

on:
  workflow_dispatch:
    # Manual trigger only for testing
  pull_request:
    branches: [ main ]
    paths:
      - '**.py'
      - 'requirements.txt'
      - '.github/workflows/**'

jobs:
  test-integrations:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Run syntax checks
      run: |
        python -m py_compile *.py
        
    - name: Test with dummy credentials (dry run)
      run: |
        # Create dummy credentials for testing imports
        echo '{"type": "service_account"}' > credentials.json
        export SLACK_BOT_TOKEN="xoxb-test"
        export SLACK_CHANNEL_ID="C123456789"
        export ZENDESK_SUBDOMAIN="test"
        export ZENDESK_EMAIL="test@example.com"
        export ZENDESK_API_TOKEN="test"
        export GOOGLE_CREDENTIALS_FILE="credentials.json"
        
        # Test imports only (no actual API calls)
        python -c "
        try:
            from calendar_monitor import CalendarMonitor
            from zendesk_client import ZendeskClient
            from slack_bot import SlackBot
            from github_actions_runner import GitHubActionsRunner
            print('✅ All imports successful')
        except Exception as e:
            print(f'❌ Import failed: {e}')
            exit(1)
        "
        
    - name: Clean up
      if: always()
      run: |
        rm -f credentials.json